# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-31 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('civilite', models.CharField(choices=[('F', 'Mme.'), ('H', 'M.')], max_length=5)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=30)),
            ],
        ),
    ]
